imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%

        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    xi_filelib:
                        dir: %kernel.root_dir%/../vendor/xi/filelib/library/Xi/Filelib/Backend/Adapter/DoctrineOrm/Entity
                        prefix: Xi\Filelib\Backend\Adapter\DoctrineOrm\Entity
                        type: annotation
                        is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

xi_filelib:
    authorization:
        enabled: false
        adapter_service: ~
#    queue:
#        type: Xi\Filelib\Queue\PhpAMQPQueue
#        arguments: [ "%amqp_host%", 5672, "%amqp_username%", "%amqp_password%", "filelib", "filelib_exchange", "filelib_queue" ]
#    slugifier:
#        type: Xi\Filelib\Tool\Slugifier\Zend2Slugifier
#    transliterator:
#        type: Xi\Filelib\Tool\Transliterator\StupidTransliterator
#        arguments: []
    renderer:
        enable_acceleration: false
        strip_prefix: "%kernel.root_dir%/data/files"
        add_prefix: "/protected"
#    cache: default
    temp_dir: %kernel.root_dir%/data/temp
#    backend:
#        platform:
#            doctrine_orm:
#                entity_manager: doctrine.orm.default_entity_manager
#                fileEntity: Xi\Filelib\Backend\Platform\DoctrineOrm\Entity\File
#                folderEntity: Xi\Filelib\Backend\Platform\DoctrineOrm\Entity\Folder
    storage:
        root: %kernel.root_dir%/data/files
        file_permission: "664"
        directory_permission: "775"
        directory_id_calculator:
            class: Xi\Filelib\Storage\Adapter\Filesystem\DirectoryIdCalculator\LeveledDirectoryIdCalculator
            arguments: [ 3, 500 ]
    publisher:
        automatic_publisher: true
        beautifurls: false
        adapter:
            class: Xi\Filelib\Publisher\Adapter\Filesystem\SymlinkFilesystemPublisherAdapter
            arguments: [ "%kernel.root_dir%/../web/files", "664", "775", "/files", "../../app/data/files" ]
    profiles: ['image_question']
    plugins:
        changeFormatPlugin:
            class: Xi\Filelib\Plugin\Image\ChangeFormatPlugin
            profiles: []
            arguments:
                -
                    0: [ setImageCompression, 8 ]
                    1: [ setImageFormat, jpg]
                    2: [ setImageCompressionQuality, 80 ]
                    3: [ scaleImage, [ 1024, 768, true ]]
                    4: [ setInterlaceScheme, 3 ]

        randomizer:
            priority: 20
            class: Xi\Filelib\Plugin\RandomizeNamePlugin
            profiles: []
            arguments:
                prefix: media

        mini:
            class: Xi\Filelib\Plugin\Image\VersionPlugin
            profiles: []
            arguments:
                -
                    mini:
                        -
                            0: [ setImageCompression, 8 ]
                            1: [ setImageFormat, jpg]
                            2: [ setImageCompressionQuality, 30 ]
                            3: [ scaleImage, [ 320, 200, true ]]
                            4: [ setInterlaceScheme, 3 ]

        cropped:
            class: Xi\Filelib\Plugin\Image\VersionPlugin
            profiles: []
            arguments:
                -
                    cropped:
                        -
                            0: [ setImageCompression, 8 ]
                            1: [ setImageFormat, jpg]
                            2: [ setImageCompressionQuality, 30 ]
                            3: [ scaleImage, [ 100, 100, 1 ]]
                            4: [ setInterlaceScheme, 3 ]

        cinemascope:
            class: Xi\Filelib\Plugin\Image\VersionPlugin
            profiles: []
            arguments:
                -
                    cinemascope:
                        -
                            0: [ setImageCompression, 8 ]
                            1: [ setImageFormat, jpg]
                            2: [ setImageCompressionQuality, 30 ]
                            3: [ scaleImage, [ 800, 200, 1 ]]
                            4: [ setInterlaceScheme, 3 ]
        thumb:
            class: Xi\Filelib\Plugin\Image\VersionPlugin
            profiles: []
            arguments:
                -
                    thumb:
                        -
                            0: [ setImageCompression, 8 ]
                            1: [ setImageFormat, jpg]
                            2: [ setImageCompressionQuality, 50 ]
                            3: [ scaleImage, [ 640, 480, 1 ]]
                            4: [ setInterlaceScheme, 3 ]
                            Xi\Filelib\Plugin\Image\Command\WatermarkCommand: [ %kernel.root_dir%/data/watermark.png, se, 10 ]
