parameters:

    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    amqp_username: ~
    amqp_password: ~
    amqp_host: ~
    amqp_vhost: ~

    zencoder_key: ~
    s3_key: ~
    s3_secretkey: ~
    s3_bucket: ~
