FilelibDemoBundle_homepage:
    pattern:  /
    defaults: { _controller: FilelibDemoBundle:Default:index }

FilelibDemoBundle_upload:
    pattern:  /upload
    defaults: { _controller: FilelibDemoBundle:Default:upload }

FilelibDemoBundle_clear:
    pattern:  /clear
    defaults: { _controller: FilelibDemoBundle:Default:clear }
