parameters:
    filelib_configurator.class: Filelib\Bundle\DemoBundle\Service\FilelibConfiguratorService

services:
    xi_filelib_configurator:
        class: %filelib_configurator.class%
        arguments: [ ]
        tags:
            - { name: xi_filelib.event.listener }
